CV_Project/CV_Project/Controllers/SocialMediaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CV_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SocialMediaController : Controller
    {
        SocialMediaManager socialMediaManager = new SocialMediaManager(new EfSocialMediaDal());
        public IActionResult Index()
        {
            var values = socialMediaManager.TGetList();
            return View(values);
        }

        [HttpGet]
        public IActionResult AddSocialMedia()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddSocialMedia(SocialMedia socialMedia)
        {
            socialMediaManager.TAdd(socialMedia);
            return RedirectToAction("Index");
        }

        public IActionResult DeleteSocialMedia(int id)
        {
            var values = socialMediaManager.TGetByID(id);
            socialMediaManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditSocialMedia(int id)
        {
            var values = socialMediaManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditSocialMedia(SocialMedia socialMedia)
        {
            socialMediaManager.TUpdate(socialMedia);
            return RedirectToAction("Index");
        }
    }
}

CV_Project/CV_Project/Views/SocialMedia/AddSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia

@{
    ViewData["Title"] = "AddSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label>Sosyal Medya</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Url</label>
                    @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Icon İsim</label>
                    @Html.TextBoxFor(x => x.Icon, new { @class = "form-control" })
                </div>
                <div class="custom-control custom-switch">
                    <input type="checkbox" class="custom-control-input" id="customSwitch1" asp-for="Status">
                    <label class="custom-control-label" for="customSwitch1">Durum</label>
                </div>
                <br />
                <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "SocialMedia")'">İptal</button>
            </form>
        </div>
    </div>
</div>

CV_Project/CV_Project/Views/SocialMedia/EditSocialMedia.cshtml
@model EntityLayer.Concrete.SocialMedia

@{
    ViewData["Title"] = "AddSocialMedia";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label>ID</label>
                    @Html.TextBoxFor(x => x.SocialMediaID, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="form-group">
                    <label>Sosyal Medya</label>
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Url</label>
                    @Html.TextBoxFor(x => x.Url, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Icon İsim</label>
                    @Html.TextBoxFor(x => x.Icon, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch1" asp-for="Status">
                        <label class="custom-control-label" for="customSwitch1">Durum</label>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "SocialMedia")'">İptal</button>
            </form>
        </div>
    </div>
</div>

CV_Project/CV_Project/Views/SocialMedia/Index.cshtml
@using EntityLayer.Concrete
@model List<SocialMedia>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" class="sort" data-sort="name">#</th>
                            <th>Sosyal Medya</th>
                            <th>Url</th>
                            <th>Icon İsim</th>
                            <th>Durum</th>
                            <th>Sil</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td style="color:white; font-weight:bold">@item.SocialMediaID</td>
                                <td style="color:white">@item.Name</td>
                                <td style="color:blueviolet"><a href="@item.Url" target="_blank">Tıkla</a></td>
                                <td style="color:white">fab fa-<strong>@item.Icon</strong></td>
                                @if (item.Status == true)
                                {
                                    <td><span class="label label-success" style="color:green; font-weight:bold">Aktif</span></td>
                                }
                                else
                                {
                                    <td><span class="label label-warning" style="color: red; font-weight: bold">Pasif</span></td>
                                }
                                <td><a href="/SocialMedia/DeleteSocialMedia/@item.SocialMediaID" class="btn btn-outline-danger" onclick="return confirm('Gerçekten silmek istiyor musunuz?')">Sil</a></td>
                                <td><a href="/SocialMedia/EditSocialMedia/@item.SocialMediaID" class="btn btn-outline-success">Güncelle</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
                <div style="text-align: left;">
                    <br />
                    <a href="/SocialMedia/AddSocialMedia/" class="btn btn-outline-info">Yeni Sosyal Medya Ekle</a>
                </div>
            </div>
        </div>
    </div>
</div>