CV_Project/CV_Project/Controllers/TestimonialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace CV_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TestimonialController : Controller
    {
        TestimonialsManager testimonialsManager = new TestimonialsManager(new EfTestimonialsDal());

        public IActionResult Index()
        {
            var values = testimonialsManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddTestimonial()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddTestimonial(Testimonials testimonials)
        {
            testimonialsManager.TAdd(testimonials);
            return RedirectToAction("Index");
        }
        public IActionResult DeleteTestimonial(int id)
        {
            var values = testimonialsManager.TGetByID(id);
            testimonialsManager.TDelete(values);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult EditTestimonial(int id)
        {
            var values = testimonialsManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditTestimonial(Testimonials testimonials)
        {
            testimonialsManager.TUpdate(testimonials);
            return RedirectToAction("Index");
        }
    }
}

CV_Project/CV_Project/Views/Testimonial/AddTestimonial.cshtml
@model EntityLayer.Concrete.Testimonials

@{
    ViewData["Title"] = "AddTestimonial";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <p class="card-description"> Yeni Müşteri Yorumu Ekleme Paneli </p>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label>Müşteri İsim</label>
                    @Html.TextBoxFor(x => x.ClientName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Şirketi</label>
                    @Html.TextBoxFor(x => x.Company, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Açıklama</label>
                    @Html.TextAreaFor(x => x.Comment, 8, 3, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Resim Url</label>
                    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Testimonial")'">İptal</button>
            </form>
        </div>
    </div>
</div>

CV_Project/CV_Project/Views/Testimonial/EditTestimonial.cshtml
@model EntityLayer.Concrete.Testimonials

@{
    ViewData["Title"] = "EditTestimonial";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label>ID</label>
                    @Html.TextBoxFor(x => x.TestimonialsID, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="form-group">
                    <label>Müşteri İsim</label>
                    @Html.TextBoxFor(x => x.ClientName, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Şirketi</label>
                    @Html.TextBoxFor(x => x.Company, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Açıklama</label>
                    @Html.TextAreaFor(x => x.Comment, 8, 3, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Resim Url</label>
                    @Html.TextBoxFor(x => x.ImageUrl,  new { @class = "form-control" })
                </div>
                <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Testimonial")'">İptal</button>
            </form>
        </div>
    </div>
</div>

CV_Project/CV_Project/Views/Testimonial/Index.cshtml
@using EntityLayer.Concrete
@model List<Testimonials>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

<div class="row ">
    <div class="col-12 grid-margin">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title"></h4>
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th> Müşteri Adı </th>
                                <th> Şirketi </th>
                                <th> Açıklama </th>
                                <th> Sil </th>
                                <th> Güncelle </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <img src="@item.ImageUrl" alt="image" />
                                        <span class="pl-2" style="color:white">@item.ClientName</span>
                                    </td>
                                    <td style="color:white" font-weight:bold"> @item.Company </td>
                                    <td style="white-space:pre-line; color:white ;text-anchor:start; text-align:center"> @item.Comment </td>
                                    <td><a href="/Testimonial/DeleteTestimonial/@item.TestimonialsID" class="btn btn-outline-danger" onclick="return confirm('Gerçekten silmek istiyor musunuz?')">Sil</a></td>
                                    <td><a href="/Testimonial/EditTestimonial/@item.TestimonialsID" class="btn btn-outline-success">Güncelle</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    <div style="text-align: left;">
                        <br />
                        <a href="/Testimonial/AddTestimonial/" class="btn btn-outline-info">Yeni Müşteri Yorumu Ekle</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>